/**
 * lang-en v1.0.0 —— English dictionary for the core i18n engine (assets/js/i18n.js).
 *
 * Keys are the EXACT Chinese UI strings as they appear in the DOM
 * (text nodes trimmed, or placeholder/title/aria-label attributes).
 * User content (messages, nicknames, room names) is never translated:
 * the engine skips #owMessages / #owRoomList / #owOnlineList entirely,
 * and free text will not match these keys as a whole node anyway.
 *
 * Add entries: grep the exact string in assets/js/chat.js / index.php first.
 */
(function (w, d) {
    'use strict';
    if (!w.OwI18n) return;

    var dict = {
        /* ---------- auth pages (index.php renderAuth) ---------- */
        '登录': 'Sign in',
        '注册': 'Register',
        '找回密码': 'Reset password',
        '欢迎回来': 'Welcome back',
        '创建账号': 'Create account',
        '注册成功，请使用注册邮箱或用户 ID 登录。': 'Registered. Sign in with your email or user ID.',
        '邮箱或用户 ID': 'Email or user ID',
        '注册邮箱或用户 ID': 'Registered email or user ID',
        '密码': 'Password',
        '图形验证码': 'Captcha',
        '验证码': 'Captcha',
        '点击刷新': 'Click to refresh',
        '登 录': 'Sign in',
        '注 册': 'Register',
        '注册账号': 'Create account',
        '忘记密码': 'Forgot password?',
        '返回聊天': 'Back to chat',
        '返回登录': 'Back to sign in',
        '已有账号，去登录': 'Have an account? Sign in',
        '昵称': 'Nickname',
        '2-20 个字符，支持中英文': '2-20 characters, letters of any language',
        '邮箱': 'Email',
        '注册邮箱': 'Email',
        '发验证码': 'Send code',
        '邮箱验证码': 'Email code',
        '新密码': 'New password',
        '重置密码': 'Reset password',
        '至少 6 位': 'At least 6 characters',
        '注册需要邮箱验证码。': 'Registration requires an email verification code.',
        '当前未开启邮箱验证，邮箱仅用于找回密码。': 'Email verification is off; the email is only used for password recovery.',

        /* ---------- chat page shell ---------- */
        '输入消息，按 Enter 发送，Ctrl+V 粘贴图片': 'Type a message. Enter to send, Ctrl+V to paste an image',
        '加入群聊后即可发言': 'Join the room to chat',
        '你还没有加入该群聊，加入后即可发言': 'You have not joined this room yet. Join to start chatting.',
        '加入群聊': 'Join room',
        '所有成员': 'Members',
        '还没有成员': 'No members yet',
        '搜索成员': 'Search members',
        '群聊设置': 'Room settings',
        '群公告': 'Announcements',
        '消息': 'Messages',
        '联系人': 'Contacts',
        '创建群聊': 'New room',
        '发送图片': 'Send image',
        '发送文件': 'Send file',
        '表情': 'Emoji',
        '设置': 'Settings',
        '退出登录': 'Sign out',
        '管理后台': 'Admin',
        '返回前台': 'Back to site',
        '群主': 'Owner',
        '会员': 'Member',
        '游客': 'Guest',
        '可发言': 'Can speak',
        '暂无会话': 'No conversations yet',
        '还没有联系人，去「成员管理」或资料卡添加吧': 'No contacts yet — add some from the member list or a profile card',
        '未加入': 'Not joined',
        '置顶': 'Pin',
        '取消置顶': 'Unpin',
        '删除好友': 'Remove contact',
        '添加好友': 'Add contact',
        '添加联系人': 'Add contact',
        '删除联系人': 'Remove contact',
        '已是好友': 'Already a contact',
        '会话': 'Conversation',
        '私聊': 'Direct message',
        '群聊': 'Room',
        '公开': 'Public',
        '不公开': 'Private',
        '密码房': 'Password room',

        /* ---------- message context menu ---------- */
        '查看个人资料': 'View profile',
        '发私信': 'Direct message',
        '私信': 'Direct message',
        '复制': 'Copy',
        '引用': 'Quote',
        '回复': 'Reply',
        '删除': 'Delete',
        '撤回': 'Recall',
        '收藏为贴纸': 'Save as sticker',
        '举报': 'Report',
        '禁言': 'Mute',
        '操作': 'Actions',
        '数量': 'Count',
        '目标': 'Target',
        '扩展名': 'Extension',

        /* ---------- room create / settings modal ---------- */
        '群名称': 'Room name',
        '群简介': 'Description',
        '公开群聊': 'Public room',
        '取消': 'Cancel',
        '保存': 'Save',
        '确定': 'OK',
        '确认': 'Confirm',
        '关闭': 'Close',
        '搜索': 'Search',
        '重置': 'Reset',
        '名称': 'Name',
        '状态': 'Status',
        '时间': 'Time',
        '类型': 'Type',
        '大小': 'Size',
        '操作人': 'Operator',
        '原因': 'Reason',
        '正常': 'Active',
        '成功': 'OK',
        '失败': 'Failed',
        '错误': 'Error',
        '跳过': 'Skipped',

        /* ---------- toasts (exact match; also covers API msg via OwI18n.t) ---------- */
        '已加入群聊': 'Joined the room',
        '群聊信息已更新': 'Room info updated',
        '群聊信息已变化，请重新打开': 'Room info changed, please reopen',
        '头像已上传': 'Avatar uploaded',
        '群头像已上传，点击保存生效': 'Room avatar uploaded — hit Save to apply',
        '请先选择一个会话': 'Select a conversation first',
        '请先选择一个联系人': 'Select a contact first',
        '请先从左侧选择一个群聊': 'Pick a room from the left first',
        '请先加入该群聊后再发言': 'Join this room before sending messages',
        '未选择群聊': 'No room selected',
        '请先选择批量操作': 'Choose a bulk action first',
        '请先勾选要操作的项目': 'Select items first',
        '游客暂不支持私聊': 'Guests cannot use direct messages yet',
        '游客没有个人资料': 'Guests have no profile',
        '游客用户无法查看资料卡': 'Guests cannot view profile cards',
        '游客不支持搜索成员': 'Guests cannot search members',
        '游客暂不支持搜索': 'Guests cannot search yet',
        '私聊对象不合法': 'Invalid direct-message target',
        '无法确定私聊对象': 'Cannot resolve the direct-message target',
        '私聊会话没有群聊设置': 'Direct chats have no room settings',
        '该群聊当前不可进入': 'This room is currently unavailable',
        '该消息所在的群聊已不可进入': 'The room of this message is no longer available',
        '裁剪弹窗已关闭': 'Crop dialog closed',
        '当前浏览器无法处理图片，请更换浏览器': 'This browser cannot process images — try another one',
        '上传失败，请重试': 'Upload failed, please retry',
        '文件上传中…': 'Uploading file…',
        '图片上传中…': 'Uploading image…',
        '上传中…': 'Uploading…',
        '保存中…': 'Saving…',
        '搜索中…': 'Searching…',
        '验证中…': 'Verifying…',
        '已复制': 'Copied',
        '复制失败，请手动选择文本': 'Copy failed — select the text manually',
        '请输入对方的用户 ID（数字）': 'Enter the other user ID (digits)',
        '请输入密码': 'Enter the password',
        '该房间需要密码': 'This room requires a password',
        '房间密码错误': 'Wrong room password',
        '没有找到匹配的用户': 'No matching users',
        '没有找到相关内容': 'Nothing found',
        '输入关键词开始搜索': 'Type a keyword to search',
        '仅显示本站注册用户。': 'Registered users only.',
        '文件内容已失效': 'File unavailable',
        '该消息已删除': 'Message deleted',
        '此消息已撤回': 'Message recalled',
        '图片': 'Image',
        '文件': 'File',
        '下载': 'Download',
        '预览': 'Preview',

        /* ---------- admin console ---------- */
        '群聊审核': 'Room review',
        '安全日志': 'Security log',
        '维护任务': 'Maintenance',
        '系统设置': 'System settings',
        '插件管理': 'Plugins',
        '基本信息': 'General',
        '注册登录': 'Registration',
        '游客、存储': 'Guests & storage',
        '系统与维护': 'System',
        '语言': 'Language',
        '保存设置': 'Save settings',
        '参数已保存': 'Settings saved',
        '配置已保存': 'Settings saved',
        '站点默认语言': 'Default site language',
        '简体中文（默认，不翻译）': 'Simplified Chinese (default, no translation)',
        '版本号': 'Version',
        '系统升级': 'System upgrade',
        '检查更新': 'Check for updates',
        '检查中…': 'Checking…',
        '清理 OPcache': 'Clear OPcache',
        '刷新页面': 'Reload',
        '运行缓存': 'Runtime cache',
        '立即执行全部': 'Run all now',
        '启用': 'Enable',
        '停用': 'Disable',
        '卸载': 'Uninstall',
        '安装': 'Install',
        '已启用': 'Enabled',
        '未启用': 'Disabled',
        '任务': 'Task',
        '说明': 'Description',
        '间隔': 'Interval',
        '下次执行': 'Next run',
        '最近执行': 'Last run',
        '结果': 'Result',
        '耗时': 'Duration',
        '信息': 'Info',
        '执行日志': 'Run log',
        '从未执行': 'Never run',
        '小时': 'hour(s)',
        '分钟': 'minute(s)',
        '天': 'day(s)',

        /* ---------- icons / tooltips / titles (found by DOM coverage probe) ---------- */
        '菜单': 'Menu',
        '发送': 'Send',
        '收起': 'Collapse',
        '收起侧栏': 'Collapse sidebar',
        '提示音': 'Sound',
        '群聊信息': 'Room info',
        '群聊信息（改名与简介）': 'Room info (name & description)',
        '我的贴纸': 'My stickers',
        '嵌入代码': 'Embed code',
        '条未读': 'unread',
        '拖动调整输入框高度': 'Drag to resize the input',
        '查看与发布本群公告': 'View and post room announcements',
        '点击查看原消息': 'View the original message',
        '管理员': 'Admin',

        /* ---------- admin: plugin names (sidebar / list) ---------- */
        '等级信任': 'Level & trust',
        '附件上传': 'Attachments',
        '页头页脚': 'Header & footer',
        '登录日志': 'Login log',
        '群聊嵌入': 'Room embed',
        '群聊公告': 'Room announcements',
        '禁言管理': 'Mute manager',
        '内容举报': 'Content report',
        '私聊合规查阅': 'DM compliance review',
        '昵称保留': 'Nickname guard',
        '敏感词过滤': 'Sensitive words',
        '两步验证': 'Two-factor',
        '用户管理': 'User manager',

        /* ---------- admin: system settings page ---------- */
        '站点、注册控制、游客与发言限制、存储方式。点分组标题展开对应设置。': 'Site, registration, guest and speaking limits, storage. Open a group to edit its settings.',
        '站点名称': 'Site name',
        '固定网站地址': 'Fixed site URL',
        '开放注册': 'Open registration',
        '注册需邮箱验证': 'Registration requires email verification',
        '注册最低年龄(周岁)': 'Minimum registration age',
        '填 0 表示不限制；填 18 则注册时必须选择出生日期且年满 18 周岁（按日期精确计算）。': '0 means no limit. 18 makes the birth date mandatory and requires a full 18 years (calculated by date).',
        '登录失败几次后要求验证码': 'Require a captcha after N failed logins',
        '登录失败几次后锁定': 'Lock after N failed logins',
        '锁定时长(分钟)': 'Lock duration (minutes)',
        '登录保护：验证码填错也计入失败次数（保证锁定可达），锁定按「账号+IP」记录，成功后清零。全部填 0 表示关闭对应保护。': 'Login guard: a wrong captcha also counts as a failure (so the lock is reachable). Locks are recorded per account + IP and clear on success. All zeros disables each guard.',
        '允许用户创建群聊': 'Users may create rooms',
        '允许用户创建仅邀请群聊': 'Users may create invite-only rooms',
        '密码房通行缓存(秒)': 'Password room pass cache (seconds)',
        '验证一次密码后，该时间内进入同一房间无需重复输入；填 0 表示每次进入都要输入。': 'After one password check, re-entering the same room within this window asks nothing; 0 means ask every time.',
        '创建群聊：管理员创建始终免费。用户创建的群聊 owner 归属创建者，可在群聊管理中调整。': 'Room creation: always free for admins. A user-created room belongs to its creator; ownership can be changed in room management.',
        '仅邀请群聊只靠邀请链接传播，不出现在任何列表里。关闭后普通用户只能创建公开群聊，已存在的仅邀请群仍可正常改名、改简介（仅禁止把公开群改成仅邀请）；管理员始终不受此限制。': 'Invite-only rooms travel only by their link and appear in no list. When off, regular users can create public rooms only; existing invite-only rooms keep their name and description editing (only public → invite-only is blocked). Admins are never limited.',
        '游客可浏览': 'Guests may browse',
        '游客可发言': 'Guests may speak',
        '游客发言间隔(秒)': 'Guest speaking interval (seconds)',
        '发言频率窗口(秒)': 'Rate window (seconds)',
        '窗口内最大条数': 'Max messages per window',
        '邮件发送间隔(秒)': 'Email send interval (seconds)',
        '消息服务器保留期(天)': 'Server message retention (days)',
        '超过本期限的消息会被': 'Messages past this limit are',
        '物理删除': 'physically deleted',
        '，其附件文件（uploads/file/）一并删除，': ' — their attachment files under uploads/file/ go with them,',
        '删除后无法恢复': 'unrecoverable once gone',
        '。默认 90 天（约三个月）。填 0 表示永久保留。': '. Default 90 days. 0 keeps everything forever.',
        '」只在本机生效（仅你看不到，别人照常看得到）；「': '” hides it on this device only (you stop seeing it, everyone else still does); “',
        '」才是全局删除，所有人都不再显示且不可恢复。': '” is the global delete: hidden for everyone and unrecoverable.',
        '新消息提示音默认': 'New message sound by default',
        '调试模式': 'Debug mode',
        '开启后记录 debug 级日志、出错页显示详细报错。仅用于排错，用完请及时关闭 —— 报错细节可能暴露路径、SQL 与配置信息。': 'Logs debug-level entries and shows detailed errors. For troubleshooting only — turn it off when done: error details can leak paths, SQL and configuration.',
        '日志文件：data/logs/debug.log（页面报错实时显示；接口请求只落日志、不回显，避免破坏前端数据）。也可在「安全日志 → 系统日志」查看与清空。': 'Log file: data/logs/debug.log (page errors show live; API requests only write to the log, so front-end data stays intact). Also viewable and clearable under Security log → System log.',
        '刷新已编译脚本缓存，适合代码更新后手动触发。PHP 会把源码编译成字节码缓存在内存里（OPcache），更新文件后若仍跑旧代码（尤其是关闭了时间戳校验时），清一次缓存即可立即生效。开启调试模式时会写 data/logs/debug.log，本操作不影响它。': 'Flushes compiled bytecode. PHP caches compiled source in memory (OPcache); if files changed but old code still runs (especially with timestamp validation off), one flush applies the update. Debug mode writes data/logs/debug.log, which this does not touch.',
        '按 GitHub 仓库逐文件比对，只更新有差异的代码文件。保护路径永不动：core/config.php、data/、uploads/；覆盖前自动备份到 data/backup/，可一键恢复。需服务器能访问 api.github.com；搬入阶段文件瞬时替换，避开高峰操作。': 'Compares the GitHub repository file by file and updates only what differs. Protected paths are never touched: core/config.php, data/, uploads/. Before overwriting, a backup goes to data/backup/ for one-click restore. Requires outbound access to api.github.com; files swap momentarily during the move, so avoid busy hours.',
        '只翻译系统界面文字（含提示），聊天消息、昵称、群名等用户内容不翻译。访客在登录页右上角切换后以自己的选择为准；保存默认语言会清掉你本浏览器的个人选择，立即按新默认显示。': 'Translates interface text and notices only — messages, nicknames and room names stay as written. A visitor who switches language on the sign-in page keeps their own choice; saving a default here clears this browser’s personal choice so the new default shows at once.',

        /* ---------- system notices (v1.3.52) ---------- */
        '通知': 'Notices',
        '系统通知': 'System notice',
        '暂无系统通知': 'No system notices yet',
        '加载中…': 'Loading…',
        '系统通知不能回复': 'System notices cannot be replied to',
        '你的登录密码已修改。如果不是你本人操作，请立即再次修改密码并检查账号安全。': 'Your login password was changed. If this wasn’t you, change it again right away and review your account security.',
        '你的账号邮箱已修改。如果不是你本人操作，请立即联系管理员。': 'Your account email was changed. If this wasn’t you, contact an administrator right away.',
        '两步验证已开启，之后登录需要输入动态验证码。': 'Two-factor authentication is now on; signing in will require a one-time code.',
        '两步验证已关闭，登录不再需要动态验证码。': 'Two-factor authentication is now off; signing in no longer needs a one-time code.',
        '你的账号已被管理员封禁，暂时无法登录与发言。': 'Your account was suspended by an administrator. You cannot sign in or post for now.',
        '你的账号已被解封，可以正常登录与发言。': 'Your account suspension was lifted. You can sign in and post again.',
        // v1.3.56：通知改存 kind + 参数，前端拿**整条模板**翻译后再填 {room_id} / {hours}，
        // 所以这里的键就是带占位符的模板原文（占位符原样保留，不要翻成 {小时}）。
        '你在群聊 #{room_id} 被禁言 {hours} 小时。': 'You were muted for {hours} hour(s) in group chat #{room_id}.',
        '你在群聊 #{room_id} 被永久禁言。': 'You were permanently muted in group chat #{room_id}.',
        '你的账号被全站禁言 {hours} 小时。': 'Your account was muted site-wide for {hours} hour(s).',
        '你的账号被全站永久禁言。': 'Your account was permanently muted site-wide.',

        /* ---------- server API messages (routed through OwI18n.t in the toast) ---------- */
        '需要管理员权限': 'Admin permission required',
        '请先登录': 'Sign in first',
        '需要登录后操作': 'Sign in to continue',
        '请先登录后再操作': 'Sign in to continue',
        '请先登录后再邀请成员': 'Sign in before inviting members',
        '请登录后再创建群聊': 'Sign in before creating a room',
        '群聊不存在': 'Room not found',
        '无权访问该群聊': 'You cannot access this room',
        '非法群聊': 'Invalid room',
        '用户不存在': 'User not found',
        '非法用户': 'Invalid user',
        '未接收到文件': 'No file received',
        '文件不存在': 'File not found',
        '请选择 zip 文件': 'Choose a zip file',
        '远程链接需以 https:// 开头': 'Remote links must start with https://',
        '本站强制 HTTPS，请通过 https:// 地址重试': 'This site requires HTTPS — retry over an https:// address',
        '无法确定站点主机，请直接使用 https:// 地址访问': 'Cannot determine the site host — open the https:// address directly',
        '请提供远程链接或上传文件': 'Provide a remote link or upload a file',
        '已更新': 'Updated',
        '已保存': 'Saved',
        '设置已保存': 'Settings saved',
        '已删除': 'Deleted',
        '已添加': 'Added',
        '已禁言': 'Muted',
        '未知操作': 'Unknown action',
        '参数错误': 'Invalid parameters',
        '无权访问': 'Access denied',
        '页面不存在': 'Page not found',
        '非法类型': 'Invalid type',
        '非法角色': 'Invalid role',
        '非法状态': 'Invalid status',
        '非法 ID': 'Invalid ID',
        '非法的公告 ID': 'Invalid announcement ID',
        '非法的群类型': 'Invalid room type',
        '日志文件不存在': 'Log file not found',
        '敏感词不能为空': 'The keyword cannot be empty',
        '举报理由不能为空': 'A report reason is required',
        '请选择举报理由': 'Pick a report reason',
        '请填写补充说明': 'Add a note',
        '请输入关键词': 'Type a keyword',
        '请填写用户 ID': 'Enter the user ID',
        '请填写有效的用户 ID': 'Enter a valid user ID',
        '请填写禁言目标': 'Choose who to mute',
        '邮箱格式不正确': 'That email address is not valid',
        '该邮箱未注册': 'That email is not registered',
        '该邮箱已注册': 'That email is already registered',
        '请填写图形验证码': 'Enter the captcha',
        '验证码错误，请输入验证器 App 中的 6 位数字': 'Wrong code — enter the 6 digits from your authenticator app',
        '验证已超时，请重新登录': 'Verification timed out, please sign in again',
        '验证通过': 'Verified',
        '请先启用两步验证': 'Enable two-factor authentication first',
        '起始日期格式应为 YYYY-MM-DD': 'The start date must be YYYY-MM-DD',
        '站点未开放用户创建群聊': 'This site does not let users create rooms',
        '邀请码已重置，旧链接立即失效': 'Invite link reset — the old link no longer works',
        '超级管理员（1 号账号）用户组已被锁定，不可修改': "The super admin's (user 1) group is locked and cannot be changed",
        '超级管理员（1 号账号）不可禁用': 'The super admin (user 1) cannot be disabled',
        '默认群聊不可恢复为删除前状态': 'The default room cannot be restored to its pre-deletion state',
        '该群聊已存在，无需恢复': 'That room already exists — nothing to restore',
        '该记录已撤销过': 'This entry has already been reverted',

        /* ---------- remaining front-end toasts ---------- */
        '举报功能不可用': 'Reporting is unavailable',
        '请先打开群聊设置弹窗': 'Open the room settings first',
        '上传头像需要启用「附件上传」插件；也可以在头像设置里选「浏览插图」': 'Uploading an avatar needs the Attachments plugin — or pick a Browse illustration in the avatar settings',
        '上传群头像需要启用「附件上传」插件；也可以选「浏览插图」': 'Uploading a room avatar needs the Attachments plugin — or pick a Browse illustration',

        /* ---------- appearance settings: day/night + color schemes (v1.3.50) ---------- */
        '日夜模式': 'Day / night mode',
        '浅色': 'Light',
        '深色': 'Dark',
        '跟随系统': 'System',
        '跟随系统会随操作系统的深浅色设置自动切换。': 'Follows your operating system’s light or dark setting.',
        '色系': 'Color scheme',
        '经典蓝': 'Classic blue',
        '翡翠绿': 'Emerald',
        '品牌红': 'Brand red',
        '紫罗兰': 'Violet',
        '猛男粉': 'Pink',
        '雅酷黑': 'Ink',
        '色系名称': 'Scheme name',
        '主色': 'Brand',
        '悬浮': 'Hover',
        '浅底': 'Tint',
        '新增色系': 'Add scheme',
        '删除该色系': 'Delete this scheme',
        '色系已删除': 'Scheme deleted',
        '请先填写色系名称': 'Give the scheme a name first',
        '色系保存失败，请检查颜色值': 'Could not save the scheme — check the colour values',
        '自建色系已达 20 个上限，删除后才能再加。': 'Custom schemes are capped at 20 — delete one to add another.',
        '内置 6 套 + 自建（最多 20 个），只改界面配色、不动消息内容，且仅对本浏览器生效。深色档下主色会自动提到可读亮度，所以同一色系在深浅两档看起来不完全一样。删除正在使用的色系会回到经典蓝。': 'Six built-in schemes plus up to 20 custom ones. Only interface colours change — messages are untouched, and the choice lives in this browser. In dark mode the brand colour is lifted to a readable brightness, so the same scheme looks different between the two modes. Deleting the scheme in use falls back to Classic blue.',

        /* ---------- human verification plugin (captcha-verify, v1.3.54) ---------- */
        '人机验证': 'Human verification',
        '服务端二次验证': 'Server-side verification',
        '关闭（用系统图形码）': 'Off (use the built-in image code)',
        '开启（取代图形码）': 'On (replaces the image code)',
        '验证服务商': 'Provider',
        '极验 Geetest v4': 'GeeTest v4',
        '实例地址': 'Instance URL',
        '组件脚本地址': 'Widget script URL',
        '验证单元 VID': 'Unit VID',
        '验证单元 KEY': 'Unit KEY',
        '测试校验连通性': 'Test connectivity',
        '切换到此服务商需重新填写': 'Fill again to switch to this provider',
        '请先完成人机验证': 'Please complete the human verification first',
        '人机验证未正确配置，请联系管理员': 'Human verification is not configured correctly — please contact an administrator',
        '人机验证组件加载失败，请刷新页面': 'The verification widget failed to load — please reload the page',
        '验证失败，请重试': 'Verification failed, please try again',
        '未知的验证服务商': 'Unknown verification provider',
        '请填写该服务商的全部必填项': 'Fill in every required field for this provider',
        '未开启或配置不完整，无法测试': 'Not enabled or incompletely configured — nothing to test',
        'VAPTCHA 脚本加载失败': 'Failed to load the VAPTCHA script',
        '未配置 VAPTCHA 验证单元 VID': 'VAPTCHA unit VID is not configured',
        '极验脚本加载失败': 'Failed to load the GeeTest script',
        '未配置极验 captcha_id': 'GeeTest captcha_id is not configured',
        '接口返回通过（异常，请检查服务商设置）': 'The API reported success (unexpected — check your provider settings)',

        /* ---------- change password in personal settings (v1.3.55) ---------- */
        '个人设置': 'Settings',
        '账号安全': 'Account security',
        '修改登录密码': 'Change password',
        '需要当前密码与邮箱验证码；改完当前设备不会掉线。': 'Needs your current password plus an emailed code. This device stays signed in.',
        '账号还没有可用邮箱，本次只验证当前密码。': 'This account has no usable email address, so only the current password is checked.',
        '账号邮箱': 'Account email',
        '当前密码': 'Current password',
        '确认新密码': 'Confirm new password',
        '验证码发到账号绑定的邮箱，有效期内只能用一次。': 'The code goes to the email on your account and can be used once.',
        '发送至': 'Sends to',
        '确认修改': 'Confirm',
        '提交中…': 'Submitting…',
        '请填写当前密码': 'Enter your current password',
        '新密码至少 6 位': 'The new password needs at least 6 characters',
        '两次输入的新密码不一致': 'The two new passwords do not match',
        '新密码不能与当前密码相同': 'The new password must differ from the current one',
        '密码已修改': 'Password changed',
        '修改密码': 'Change password',
        '当前密码不正确': 'That current password is not correct',
        '账号不存在或已被禁用': 'The account does not exist or is disabled',
        '请填写邮箱': 'Enter an email address',
        '站点未开启邮箱验证码': 'Email verification codes are switched off on this site',
        '站点未启用邮件发送（未安装或未配置邮件插件），请联系管理员': 'This site cannot send email — no mail plugin is installed and configured. Please contact an administrator.',
        '该邮箱本小时的发送次数已达上限，请稍后再试': 'This mailbox hit its hourly send limit — please try again later',
        '当前 IP 邮件发送已达上限，请稍后再试': 'This IP address hit its hourly email limit — please try again later',
        '当前浏览器本小时的发送次数已达上限，请稍后再试': 'This browser hit its hourly send limit — please try again later',
        '站点当前不可用邮箱验证码（未开启，或未配置能发信的邮件插件），无法自助找回密码。请联系管理员在后台处理。': 'Self-service password reset needs an emailed code, which this site cannot provide right now (switched off, or no working mail plugin). Please contact an administrator.',

        /* ---------- email plugin (email-verify, v1.3.55) ---------- */
        '邮箱验证': 'Email verification',
        '发送通道': 'Delivery channel',
        '启用邮件发送': 'Send email',
        '关闭（验证码发不出去）': 'Off (codes cannot be delivered)',
        '通道类型': 'Channel type',
        'SMTP（推荐）': 'SMTP (recommended)',
        'PHP mail()（依赖本机 MTA）': 'PHP mail() (needs a local MTA)',
        'SMTP 服务器': 'SMTP server',
        '端口': 'Port',
        '加密方式': 'Encryption',
        'SSL（465）': 'SSL (465)',
        'STARTTLS（587）': 'STARTTLS (587)',
        '明文（仅内网）': 'Plaintext (intranet only)',
        '账号': 'Account',
        '密码 / 授权码': 'Password / app token',
        '完整的发件邮箱': 'Full sender address',
        'QQ / 163 需用授权码，不是登录密码': 'QQ and 163 need an app token, not the login password',
        '已保存，留空即不修改': 'Saved — leave blank to keep it',
        '发件地址': 'Sender address',
        '发件人名称': 'Sender name',
        '留空则用站点名': 'Blank uses the site name',
        '发测试邮件给我': 'Send me a test email',
        '测试邮件只会发到当前登录管理员自己账号的邮箱，不会给任意地址发信。': 'The test email goes only to the mailbox of the administrator signed in right now — never to an arbitrary address.',
        '验证码与限流': 'Codes and rate limits',
        '有效期（分钟）': 'Code validity (minutes)',
        '重发间隔（秒）': 'Resend interval (seconds)',
        '单邮箱每小时上限': 'Per mailbox per hour',
        '单 IP 每小时上限': 'Per IP per hour',
        '单浏览器每小时上限': 'Per browser per hour',
        '最多输错次数': 'Wrong attempts allowed',
        '邮箱最小长度': 'Minimum email length',
        '邮箱最大长度': 'Maximum email length',
        '0 = 不限制': '0 = unlimited',
        '允许邮箱后缀': 'Allowed email domains',
        '邮箱唯一检查': 'Require a unique email',
        '允许用户修改邮箱': 'Let users change their email',
        '开启邮箱验证码': 'Email verification codes',
        '保存策略': 'Save policy',
        '策略已保存': 'Policy saved',
        '邮件模板': 'Email templates',
        '场景': 'Scenario',
        '当前来源': 'Currently from',
        '主题': 'Subject',
        '正文（HTML）': 'Body (HTML)',
        '保存模板': 'Save template',
        '模板已保存': 'Template saved',
        '恢复内置默认': 'Restore built-in default',
        '已恢复内置默认模板': 'The built-in default template is back in place',
        '已填入内置默认，点「保存模板」即覆盖当前自定义': 'Filled with the built-in default — press Save template to overwrite the custom one',
        '内置默认（尚未自定义）': 'Built-in default (not customised yet)',
        '后台保存的模板': 'Template saved here',
        '目录文件 data/mail-templates/（优先级最高，此处编辑不生效）': 'File in data/mail-templates/ (wins over everything edited here)',
        '发送记录': 'Delivery log',
        '今日待发送': 'Queued today',
        '今日已发': 'Sent today',
        '今日失败': 'Failed today',
        '就绪': 'Ready',
        '未就绪': 'Not ready',
        '未开启': 'Not enabled',
        '待发送': 'Queued',
        '已发': 'Sent',
        '清空记录': 'Clear log',
        '发送记录已清空': 'Delivery log cleared',
        '还没有发送记录。': 'No delivery records yet.',
        '收件邮箱': 'Recipient',
        '未知场景': 'Unknown scenario',
        '收件邮箱无效': 'The recipient address is not valid',
        '模板正文过长（上限 60000 字节）': 'The template body is too long (60000 bytes max)',
        '没有收到任何可保存的设置项': 'Nothing to save — no settings came through',
        '邮箱最小长度不能大于最大长度': 'The minimum email length cannot exceed the maximum',
        '发件地址未填或未通过格式校验': 'The sender address is empty or fails validation',
        'SMTP 服务器地址未填': 'The SMTP server address is empty',
        'SMTP 端口不合法': 'The SMTP port is not valid',
        '服务器未启用 PHP mail() 函数': 'PHP mail() is not enabled on this server',
        '配置不完整': 'Configuration incomplete',
        '请检查发件地址与 SMTP 参数': 'Check the sender address and the SMTP parameters',
        '邮件发送失败：': 'Sending failed: '
    };

    w.OwI18n.register('en', 'English', dict);
})(window, document);
